export enum Profession {
  BARBARIAN = "BARBARIAN",
  FIRE_MAGE = "FIRE_MAGE",
  DRUID = "DRUID",
  KNIGHT = "KNIGHT",
  ARCHER = "ARCHER",
  SHEED = "SHEED",
  VOODOO = "VOODOO",
  DEFAULT = "DEFAULT"
}
