export enum UpgradeTarget {
  DAMAGE = "DAMAGE",
  STRENGTH = "STRENGTH",
  DEXTERITY = "DEXTERITY",
  POWER = "POWER",
  KNOWLEDGE = "KNOWLEDGE",
  HEALTH = "HEALTH",
  MANA = "MANA",
  STAMINA = "STAMINA"
}
